services:
  colyseus:
    build:
      context: .
      dockerfile: docker/colyseus.Dockerfile
    restart: unless-stopped
    ports:
      - "2567:2567"
    environment:
      NODE_ENV: production

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
        NEXT_PUBLIC_COLYSEUS_URL: "ws://localhost:2567"
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      colyseus:
        condition: service_started
