services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3100}
        NEXT_PUBLIC_COLYSEUS_URL: ${NEXT_PUBLIC_COLYSEUS_URL:-ws://localhost:2567}
    restart: always
    ports:
      - "3100:3000"
    depends_on:
      colyseus:
        condition: service_started

  colyseus:
    build:
      context: .
      dockerfile: docker/colyseus.Dockerfile
    restart: always
    ports:
      - "2567:2567"
    environment:
      NODE_ENV: production
